RTI-3033 - Replace snyk-scan-workspaces ctrf step

diff --git a/external/ag-shared/github/actions/snyk-scan-workspaces/action.yml b/external/ag-shared/github/actions/snyk-scan-workspaces/action.yml
--- a/external/ag-shared/github/actions/snyk-scan-workspaces/action.yml
+++ b/external/ag-shared/github/actions/snyk-scan-workspaces/action.yml
@@ -34,36 +34,29 @@ runs:
           with:
               script: |
                   const fs = require('fs');
-                  fs.mkdirSync('${{ env.OUTPUT_DIR }}', { recursive: true });
+                  fs.mkdirSync('${{ inputs.output_dir }}', { recursive: true });
+
         - name: Run snyk to check for vulnerabilities on all yarn workspaces
+          id: snyk-scan
           uses: snyk/actions/node@master
+          continue-on-error: true
           env:
               SNYK_TOKEN: ${{ inputs.snyk_token }}
           with:
               args: --yarn-workspaces --dev --strict-out-of-sync=false --severity-threshold=${{ inputs.severity_threshold }} --exclude=${{ inputs.exclude }} --remote-repo-url=${{ inputs.remote_repo_url }} --json > ${{ inputs.output_dir }}${{ inputs.snyk_file }}
 
-        - name: To report CTRF format
-          uses: actions/github-script@v7
+        - name: Convert snyk report to CTRF report
+          shell: bash
           if: ${{ inputs.report_file != '' }}
           env:
-              REPORT_FILE: ${{ inputs.report_file }}
-              OUTPUT_DIR: ${{ inputs.output_dir }}
-              SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
-          with:
-              script: |
-                  const fs = require('fs');
-                  const path = require('path');
-                  const file = '${{ inputs.output_dir }}${{ inputs.snyk_file }}';
-                  const combinedResults = [];
+              SNYK_JSON_FILE: '${{ inputs.output_dir }}${{ inputs.snyk_file }}'
+              CTRF_OUTPUT_FILE: '${{ inputs.output_dir }}${{ inputs.report_file }}'
+          run: |
+              node ./external/ag-shared/scripts/snyk/snyk-to-ctrf-command.mjs
 
-                  if (fs.existsSync(file)) {
-                    combinedResults.push(...JSON.parse(fs.readFileSync(file, 'utf8')));
-                  }
-
-                  const passed = combinedResults.filter(project => project.ok).length;
-                  const vulnerabilities = combinedResults.flatMap(project => project.vulnerabilities);
-
-                  const report = {
-                    results: { summary: { failed: vulnerabilities.length, passed, skipped: 0 } }
-                  }
-                  fs.writeFileSync(path.join('${{ env.OUTPUT_DIR }}', '${{ env.REPORT_FILE }}'), JSON.stringify(report));
+        - name: Fail job if scan failed
+          shell: bash
+          if: success() && steps.snyk-scan.outcome == 'failure'
+          run: |
+              echo "Workflow failed, failing the build."
+              exit 1
