RTI-3033 - Add CTRF report to snyk dependency scan

diff --git a/.github/workflows/security.yml b/.github/workflows/security.yml
--- a/.github/workflows/security.yml
+++ b/.github/workflows/security.yml
@@ -22,6 +22,8 @@ permissions:
 env:
     OUTPUT_DIR: test-results/
     REPORT_FILE: report.json
+    SNYK_FILE: snyk.json
+    CTRF_REPORT_FILE: snyk.ctrf.json
     PREV_COMMIT_SHA_FILE: ./commit-sha.txt
     REPO_URL: ${{ github.server_url }}/${{ github.repository }}
     SLACK_CHANNEL: '#ci-grid-gate'
@@ -40,18 +42,42 @@ jobs:
             - name: Snyk scan workspaces
               id: snyk-scan-workspaces
               uses: ./external/ag-shared/github/actions/snyk-scan-workspaces
+              continue-on-error: true
               with:
                   snyk_token: ${{ secrets.SNYK_TOKEN }}
                   remote_repo_url: ${{env.REPO_URL}}
                   output_dir: ${{ env.OUTPUT_DIR }}
                   report_file: ${{ env.REPORT_FILE }}
+                  snyk_file: ${{ env.SNYK_FILE }}
+
+            - name: Convert snyk report to ctrf report
+              id: convert-snyk-ctrf
+              if: always()
+              shell: bash
+              env:
+                  SNYK_JSON_FILE: '${{ env.OUTPUT_DIR }}${{ env.SNYK_FILE }}'
+                  CTRF_OUTPUT_FILE: '${{ env.OUTPUT_DIR }}${{ env.CTRF_REPORT_FILE }}'
+              run: |
+                  node ./external/ag-shared/scripts/snyk/snyk-to-ctrf-command.mjs
+
+            - name: Publish CSP Report
+              uses: ctrf-io/github-test-reporter@v1
+              if: always()
+              with:
+                report-path: '${{ env.OUTPUT_DIR }}${{ env.CTRF_REPORT_FILE }}'
 
             - name: Persist scan results
               if: always()
               uses: actions/upload-artifact@v4
               with:
-                  name: snyk-scan-workspaces
+                  name: code-dependency-scan
                   path: ${{ env.OUTPUT_DIR }}
+
+            - name: Fail job if workflow failed
+              if: success() && steps.snyk-scan-workspaces.outcome == 'failure'
+              run: |
+                  echo "Workflow failed, failing the build."
+                  exit 1
 
     sast-code-scan:
         runs-on: ubuntu-latest
@@ -65,6 +91,7 @@ jobs:
             - name: Snyk code scan
               id: snyk-code-scan
               uses: ./external/ag-shared/github/actions/snyk-code-scan
+              continue-on-error: true
               with:
                   snyk_token: ${{ secrets.SNYK_TOKEN }}
                   output_dir: ${{ env.OUTPUT_DIR }}
@@ -74,7 +101,7 @@ jobs:
               if: always()
               uses: actions/upload-artifact@v4
               with:
-                  name: snyk-code-scan
+                  name: sast-code-scan
                   path: ${{ env.OUTPUT_DIR }}
 
     combine-scan-results:
